[2024-03-18 00:38:21,742:INFO: main:$(message)s]
[2024-03-18 00:39:30,868:INFO: main:Welcome to our Custome logs]
[2024-03-18 00:41:17,577:INFO: main:Welcome to our Custome logs removed src]
[2024-03-18 00:43:29,170:INFO: main:Welcome to our Custome logs ]
[2024-03-23 08:31:45,169:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:31:45,192:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:40:32,963:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:40:32,966:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:43:08,773:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:43:08,775:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:43:41,181:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:43:41,183:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:46:47,584:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:46:47,587:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:47:03,960:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:47:03,963:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:50:11,456:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:50:11,459:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:50:57,618:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:50:57,621:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:52:10,151:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:52:10,155:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:54:31,634:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:54:31,638:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:54:31,646:INFO: common:Created directory at : artifacts]
[2024-03-23 08:54:31,648:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 08:57:53,906:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 08:57:53,908:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 08:57:53,911:INFO: common:Created directory at : artifacts]
[2024-03-23 08:57:53,912:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 09:16:57,057:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 09:16:57,060:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 09:16:57,062:INFO: common:Created directory at : artifacts]
[2024-03-23 09:16:57,064:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 09:19:44,075:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 09:19:44,079:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 09:19:44,082:INFO: common:Created directory at : artifacts]
[2024-03-23 09:19:44,084:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 09:20:46,765:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 09:20:46,770:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 09:20:46,773:INFO: common:Created directory at : artifacts]
[2024-03-23 09:20:46,774:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 09:20:46,778:INFO: 1804010469:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 09:21:06,636:INFO: 1804010469:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 09:50:21,144:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 09:50:21,144:ERROR: main:name 'obj' is not defined]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 7, in <module>
    obj.main()
NameError: name 'obj' is not defined
[2024-03-23 09:53:28,422:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 09:53:28,425:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 09:53:28,426:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 09:53:28,426:INFO: common:Created directory at : artifacts]
[2024-03-23 09:53:28,427:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 09:53:28,428:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 10:33:27,768:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 10:33:27,771:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 10:33:27,773:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 10:33:27,774:INFO: common:Created directory at : artifacts]
[2024-03-23 10:33:27,774:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 10:33:27,775:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 10:33:47,513:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 10:33:48,606:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 17:49:25,724:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 17:51:23,970:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 17:53:36,272:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 17:54:35,054:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 17:59:12,770:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:01:22,238:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:01:48,325:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:02:26,659:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:03:27,702:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:09:08,755:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:21:28,183:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:24:27,466:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:25:41,592:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 18:25:41,597:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:25:41,600:ERROR: main:while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 32, in read_yaml
    content =yaml.safe_load(yaml_file)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54
[2024-03-23 18:33:41,688:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 18:33:41,692:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:33:41,695:ERROR: main:while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 36, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 32, in read_yaml
    content =yaml.safe_load(yaml_file)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54
[2024-03-23 18:34:48,559:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 18:34:48,564:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 18:34:48,565:ERROR: main:while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 32, in read_yaml
    content =yaml.safe_load(yaml_file)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54
[2024-03-23 20:30:14,876:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 20:31:25,745:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 20:32:12,445:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:32:12,447:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:32:34,043:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:32:34,043:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:33:00,704:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:33:00,704:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:33:13,754:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:33:13,754:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:34:32,759:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:34:32,759:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:35:33,531:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:35:33,531:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:35:51,855:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:35:51,856:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "e:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:37:32,828:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:37:32,830:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "e:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:38:15,807:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:38:15,808:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:47:24,016:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:47:24,016:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:53:44,711:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:53:44,711:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:55:38,383:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:55:38,384:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:57:57,334:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:57:57,335:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:58:11,042:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:58:11,043:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml, ) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 20:58:35,602:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 20:58:35,603:ERROR: main:[Errno 2] No such file or directory: 'config.yaml']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 13, in __init__
    self.config = read_yaml(config_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 38, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 31, in read_yaml
    with open (path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config.yaml'
[2024-03-23 21:29:57,054:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 21:29:57,057:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 21:29:57,060:ERROR: main:while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 8, in <module>
    data_ingestion.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage_01_data_ingestion.py", line 12, in main
    config = ConfigurationManager()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\config\configuration.py", line 14, in __init__
    self.params = read_yaml(params_filepath)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 40, in read_yaml
    raise e
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 34, in read_yaml
    content =yaml.safe_load(yaml_file)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 115, in check_token
    while self.need_more_tokens():
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 152, in need_more_tokens
    self.stale_possible_simple_keys()
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\yaml\scanner.py", line 291, in stale_possible_simple_keys
    raise ScannerError("while scanning a simple key", key.mark,
yaml.scanner.ScannerError: while scanning a simple key
  in "params.yaml", line 11, column 1
could not find expected ':'
  in "params.yaml", line 15, column 54
[2024-03-23 21:32:21,158:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 21:32:21,175:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 21:32:21,176:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 21:32:21,176:INFO: common:Created directory at : artifacts]
[2024-03-23 21:32:21,176:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 21:32:21,176:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:35:30,832:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:35:32,065:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 21:39:15,444:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 21:39:15,448:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 21:39:15,451:INFO: common:Created directory at : artifacts]
[2024-03-23 21:39:15,454:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 21:39:15,457:INFO: 1804010469:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:40:15,110:INFO: 1804010469:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:48:05,602:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 21:48:05,604:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 21:48:05,612:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 21:48:05,613:INFO: common:Created directory at : artifacts]
[2024-03-23 21:48:05,614:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 21:48:05,616:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:51:22,104:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 21:51:22,863:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 22:38:51,173:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:38:51,199:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:38:51,203:INFO: common:Created directory at : artifacts]
[2024-03-23 22:39:42,283:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:39:42,291:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:39:42,294:INFO: common:Created directory at : artifacts]
[2024-03-23 22:40:20,940:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:40:20,947:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:40:20,951:INFO: common:Created directory at : artifacts]
[2024-03-23 22:42:58,427:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:42:58,434:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:42:58,437:INFO: common:Created directory at : artifacts]
[2024-03-23 22:42:58,439:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-23 22:44:43,269:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:44:43,275:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:44:43,277:INFO: common:Created directory at : artifacts]
[2024-03-23 22:44:43,280:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-23 22:46:47,708:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 22:46:47,708:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 22:46:47,723:INFO: common:Created directory at : artifacts]
[2024-03-23 22:46:47,725:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-23 22:50:05,028:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-23 23:04:53,983:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 23:04:53,988:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:04:53,991:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:04:53,992:INFO: common:Created directory at : artifacts]
[2024-03-23 23:04:53,992:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 23:04:53,994:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:06:33,351:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:06:34,298:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 23:06:34,298:INFO: main:***********************************************]
[2024-03-23 23:06:34,298:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-23 23:06:34,302:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:06:34,305:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:06:34,306:INFO: common:Created directory at : artifacts]
[2024-03-23 23:06:34,306:ERROR: main:'ConfigurationManager' object has no attribute 'get_prepare_base_model_config']
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 23, in <module>
    prepare_base_model.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage02_prepare_base_model.py", line 13, in main
    prepare_base_model_config = config.get_prepare_base_model_config()
AttributeError: 'ConfigurationManager' object has no attribute 'get_prepare_base_model_config'
[2024-03-23 23:25:59,197:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 23:25:59,197:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:25:59,197:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:25:59,197:INFO: common:Created directory at : artifacts]
[2024-03-23 23:25:59,197:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 23:25:59,197:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:26:25,677:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:26:26,727:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 23:26:26,727:INFO: main:***********************************************]
[2024-03-23 23:26:26,727:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-23 23:26:26,727:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:26:26,727:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:26:26,727:INFO: common:Created directory at : artifacts]
[2024-03-23 23:26:26,727:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-23 23:26:26,727:ERROR: main:name 'PrepareBaseModel' is not defined]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 23, in <module>
    prepare_base_model.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage02_prepare_base_model.py", line 15, in main
    prepare_base_model = PrepareBaseModel(config= prepare_base_model_config)
NameError: name 'PrepareBaseModel' is not defined
[2024-03-23 23:27:30,175:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-23 23:27:30,175:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:27:30,175:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:27:30,175:INFO: common:Created directory at : artifacts]
[2024-03-23 23:27:30,175:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-23 23:27:30,175:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:28:50,242:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-23 23:28:51,139:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-23 23:28:51,139:INFO: main:***********************************************]
[2024-03-23 23:28:51,139:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-23 23:28:51,152:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-23 23:28:51,155:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-23 23:28:51,155:INFO: common:Created directory at : artifacts]
[2024-03-23 23:28:51,155:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-23 23:28:51,158:ERROR: main:local variable 'prepare_base_model' referenced before assignment]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 23, in <module>
    prepare_base_model.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage02_prepare_base_model.py", line 15, in main
    prepare_base_model = prepare_base_model(config= prepare_base_model_config)
UnboundLocalError: local variable 'prepare_base_model' referenced before assignment
[2024-03-26 19:57:55,732:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-26 19:57:55,763:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 19:57:55,780:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 19:57:55,780:INFO: common:Created directory at : artifacts]
[2024-03-26 19:57:55,783:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-26 19:57:55,784:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 19:58:28,742:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 19:58:30,362:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-26 19:58:30,362:INFO: main:***********************************************]
[2024-03-26 19:58:30,363:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-26 19:58:30,386:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 19:58:30,393:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 19:58:30,393:INFO: common:Created directory at : artifacts]
[2024-03-26 19:58:30,393:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-26 19:58:30,397:ERROR: main:local variable 'prepare_base_model' referenced before assignment]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 23, in <module>
    prepare_base_model.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage02_prepare_base_model.py", line 15, in main
    prepare_base_model = prepare_base_model(config= prepare_base_model_config)
UnboundLocalError: local variable 'prepare_base_model' referenced before assignment
[2024-03-26 20:13:28,241:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-26 20:13:28,248:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 20:13:28,261:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 20:13:28,263:INFO: common:Created directory at : artifacts]
[2024-03-26 20:13:28,265:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-26 20:13:28,267:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 20:14:00,847:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 20:14:02,089:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-26 20:14:02,089:INFO: main:***********************************************]
[2024-03-26 20:14:02,089:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-26 20:14:02,097:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 20:14:02,104:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 20:14:02,105:INFO: common:Created directory at : artifacts]
[2024-03-26 20:14:02,105:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-26 20:14:03,273:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-26 20:14:03,622:INFO: main:************************************************]
[2024-03-26 20:14:03,622:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-03-26 22:31:02,972:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:31:02,991:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:31:02,996:INFO: common:Created directory at : artifacts]
[2024-03-26 22:36:30,519:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:36:30,532:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:36:30,536:INFO: common:Created directory at : artifacts]
[2024-03-26 22:36:30,536:INFO: common:Created directory at : artifacts\training]
[2024-03-26 22:38:54,006:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:38:54,016:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:38:54,018:INFO: common:Created directory at : artifacts]
[2024-03-26 22:38:54,022:INFO: common:Created directory at : artifacts\training]
[2024-03-26 22:56:04,305:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-03-26 22:56:04,322:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:56:04,331:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:56:04,334:INFO: common:Created directory at : artifacts]
[2024-03-26 22:56:04,336:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-03-26 22:56:04,337:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 22:56:29,357:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-26 22:56:30,299:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-03-26 22:56:30,299:INFO: main:***********************************************]
[2024-03-26 22:56:30,299:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-03-26 22:56:30,303:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:56:30,305:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:56:30,306:INFO: common:Created directory at : artifacts]
[2024-03-26 22:56:30,307:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-03-26 22:56:31,091:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-26 22:56:31,370:INFO: main:************************************************]
[2024-03-26 22:56:31,370:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-03-26 22:56:31,370:INFO: main:***********************************************]
[2024-03-26 22:56:31,371:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-03-26 22:56:31,374:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-03-26 22:56:31,379:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-03-26 22:56:31,380:INFO: common:Created directory at : artifacts]
[2024-03-26 22:56:31,381:INFO: common:Created directory at : artifacts\training]
[2024-03-26 22:58:49,556:INFO: main:************************************************]
[2024-03-26 22:58:49,557:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-04 15:54:21,648:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-04 15:54:22,133:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-04 15:56:24,836:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-04 15:56:24,845:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-04 15:56:24,848:INFO: common:Created directory at : artifacts]
[2024-04-05 12:09:19,902:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:09:19,964:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:09:19,967:INFO: common:Created directory at : artifacts]
[2024-04-05 12:10:30,402:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-04-05 12:10:30,411:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:10:30,420:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:10:30,425:INFO: common:Created directory at : artifacts]
[2024-04-05 12:10:30,428:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-04-05 12:10:30,430:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 12:10:46,616:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 12:10:47,705:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-04-05 12:10:47,705:INFO: main:***********************************************]
[2024-04-05 12:10:47,706:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-04-05 12:10:47,713:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:10:47,718:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:10:47,719:INFO: common:Created directory at : artifacts]
[2024-04-05 12:10:47,719:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-04-05 12:10:48,694:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-05 12:10:48,996:INFO: main:************************************************]
[2024-04-05 12:10:48,996:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-04-05 12:10:48,997:INFO: main:***********************************************]
[2024-04-05 12:10:48,997:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-04-05 12:10:48,999:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:10:49,001:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:10:49,002:INFO: common:Created directory at : artifacts]
[2024-04-05 12:10:49,004:INFO: common:Created directory at : artifacts\training]
[2024-04-05 12:12:56,280:INFO: main:************************************************]
[2024-04-05 12:12:56,280:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-05 12:17:02,507:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:17:02,512:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:17:02,514:INFO: common:Created directory at : artifacts]
[2024-04-05 12:20:27,603:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:20:27,609:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:20:27,614:INFO: common:Created directory at : artifacts]
[2024-04-05 12:22:22,642:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:22:22,650:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:22:22,650:INFO: common:Created directory at : artifacts]
[2024-04-05 12:22:42,116:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:22:42,121:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:22:42,124:INFO: common:Created directory at : artifacts]
[2024-04-05 12:24:14,998:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 12:24:18,162:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpg7hg4ghf\model\data\model\assets]
[2024-04-05 12:30:16,636:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:30:16,654:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:30:16,659:INFO: common:Created directory at : artifacts]
[2024-04-05 12:33:01,701:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:33:01,708:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:33:01,712:INFO: common:Created directory at : artifacts]
[2024-04-05 12:47:15,671:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:47:15,676:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:47:15,679:INFO: common:Created directory at : artifacts]
[2024-04-05 12:48:40,520:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:48:40,525:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:48:40,528:INFO: common:Created directory at : artifacts]
[2024-04-05 12:49:33,143:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:49:33,148:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:49:33,151:INFO: common:Created directory at : artifacts]
[2024-04-05 12:50:16,794:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 12:50:17,737:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpj8rb1no4\model\data\model\assets]
[2024-04-05 12:51:17,807:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:51:17,813:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:51:17,816:INFO: common:Created directory at : artifacts]
[2024-04-05 12:52:48,762:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:52:48,772:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:52:48,775:INFO: common:Created directory at : artifacts]
[2024-04-05 12:53:46,938:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 12:53:47,872:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpztqmxcd6\model\data\model\assets]
[2024-04-05 12:58:22,449:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 12:58:22,464:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 12:58:22,466:INFO: common:Created directory at : artifacts]
[2024-04-05 12:59:08,300:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 12:59:09,209:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpedoh3zx4\model\data\model\assets]
[2024-04-05 13:07:53,082:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 13:07:53,167:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 13:07:53,170:INFO: common:Created directory at : artifacts]
[2024-04-05 13:08:53,325:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 13:08:54,998:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpcw37_0we\model\data\model\assets]
[2024-04-05 13:31:09,732:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-04-05 13:31:09,735:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 13:31:09,745:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 13:31:09,746:INFO: common:Created directory at : artifacts]
[2024-04-05 13:31:09,747:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-04-05 13:31:09,747:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 13:31:23,586:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 13:31:25,553:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-04-05 13:31:25,559:INFO: main:***********************************************]
[2024-04-05 13:31:25,561:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-04-05 13:31:25,568:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 13:31:25,582:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 13:31:25,583:INFO: common:Created directory at : artifacts]
[2024-04-05 13:31:25,584:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-04-05 13:31:27,085:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-05 13:31:27,350:INFO: main:************************************************]
[2024-04-05 13:31:27,350:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-04-05 13:31:27,350:INFO: main:***********************************************]
[2024-04-05 13:31:27,351:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-04-05 13:31:27,354:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 13:31:27,355:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 13:31:27,356:INFO: common:Created directory at : artifacts]
[2024-04-05 13:31:27,357:INFO: common:Created directory at : artifacts\training]
[2024-04-05 13:33:42,806:INFO: main:************************************************]
[2024-04-05 13:33:42,806:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-05 13:33:42,807:INFO: main:>>>>>>>> stage Evaluation Stage started <<<<<<<<]
[2024-04-05 13:33:42,810:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 13:33:42,813:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 13:33:42,813:INFO: common:Created directory at : artifacts]
[2024-04-05 13:34:20,647:ERROR: main:name 'indent' is not defined]
Traceback (most recent call last):
  File "E:\DATA SCIENCE\INSAID\CNNPROJECTS\kidney-disease-classification-deep-learning-project\main.py", line 55, in <module>
    obj.main()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\pipeline\stage04_model_evaluation.py", line 17, in main
    evaluation.save_score()
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\components\model_evaluation_mlflow.py", line 56, in save_score
    save_json(path = Path("scores.json"), data= scores)
  File "C:\Users\ADMIN\anaconda3\envs\kidney\lib\site-packages\ensure\main.py", line 807, in __call__
    return self.f(*args, **kwargs)
  File "e:\data science\insaid\cnnprojects\kidney-disease-classification-deep-learning-project\src\cnnClassifier\utils\common.py", line 66, in save_json
    json.dump(data, f, indent-4)
NameError: name 'indent' is not defined
[2024-04-05 14:30:00,368:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-04-05 14:30:00,371:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:30:00,373:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:30:00,373:INFO: common:Created directory at : artifacts]
[2024-04-05 14:30:00,374:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-04-05 14:30:00,375:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:30:18,015:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:30:18,912:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-04-05 14:30:18,913:INFO: main:***********************************************]
[2024-04-05 14:30:18,913:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-04-05 14:30:18,917:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:30:18,920:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:30:18,921:INFO: common:Created directory at : artifacts]
[2024-04-05 14:30:18,921:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-04-05 14:30:19,629:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-05 14:30:19,864:INFO: main:************************************************]
[2024-04-05 14:30:19,865:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-04-05 14:30:19,865:INFO: main:***********************************************]
[2024-04-05 14:30:19,865:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-04-05 14:30:19,868:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:30:19,870:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:30:19,871:INFO: common:Created directory at : artifacts]
[2024-04-05 14:30:19,871:INFO: common:Created directory at : artifacts\training]
[2024-04-05 14:32:25,413:INFO: main:************************************************]
[2024-04-05 14:32:25,414:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-05 14:32:25,414:INFO: main:>>>>>>>> stage Evaluation Stage started <<<<<<<<]
[2024-04-05 14:32:25,417:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:32:25,418:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:32:25,419:INFO: common:Created directory at : artifacts]
[2024-04-05 14:33:04,998:INFO: common:json file saved : scores.json]
[2024-04-05 14:33:10,022:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 14:33:10,970:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmp_czlbg4i\model\data\model\assets]
[2024-04-05 14:33:58,014:INFO: main:>>>>>>>> stage Evaluation Stage completed <<<<<<]
[2024-04-05 14:35:08,453:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-04-05 14:35:08,464:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:35:08,481:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:35:08,481:INFO: common:Created directory at : artifacts]
[2024-04-05 14:35:08,481:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-04-05 14:35:08,482:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:35:22,032:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:35:23,159:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-04-05 14:35:23,159:INFO: main:***********************************************]
[2024-04-05 14:35:23,159:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-04-05 14:35:23,165:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:35:23,171:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:35:23,171:INFO: common:Created directory at : artifacts]
[2024-04-05 14:35:23,172:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-04-05 14:35:24,035:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-05 14:35:25,071:INFO: main:************************************************]
[2024-04-05 14:35:25,071:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-04-05 14:35:25,072:INFO: main:***********************************************]
[2024-04-05 14:35:25,072:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-04-05 14:35:25,080:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:35:25,086:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:35:25,087:INFO: common:Created directory at : artifacts]
[2024-04-05 14:35:25,089:INFO: common:Created directory at : artifacts\training]
[2024-04-05 14:40:04,785:INFO: main:************************************************]
[2024-04-05 14:40:04,786:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-05 14:40:04,786:INFO: main:>>>>>>>> stage Evaluation Stage started <<<<<<<<]
[2024-04-05 14:40:04,799:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:40:04,803:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:40:04,804:INFO: common:Created directory at : artifacts]
[2024-04-05 14:40:42,370:INFO: common:json file saved : scores.json]
[2024-04-05 14:40:46,759:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 14:40:47,827:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpk6w8giyr\model\data\model\assets]
[2024-04-05 14:41:31,328:INFO: main:>>>>>>>> stage Evaluation Stage completed <<<<<<]
[2024-04-05 14:42:27,546:INFO: main:>>>>>>>> stage Data Ingestion Stage started <<<<<<<<]
[2024-04-05 14:42:27,549:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:42:27,561:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:42:27,562:INFO: common:Created directory at : artifacts]
[2024-04-05 14:42:27,562:INFO: common:Created directory at : artifacts/data_ingestion]
[2024-04-05 14:42:27,562:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:42:41,581:INFO: data_ingestion:Downloading data from  https://drive.google.com/file/d/16HtdVLJl7ItqJhiQkvTTLMkbhijb5197/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-04-05 14:42:42,448:INFO: main:>>>>>>>> stage Data Ingestion Stage completed <<<<<<]
[2024-04-05 14:42:42,448:INFO: main:***********************************************]
[2024-04-05 14:42:42,448:INFO: main:>>>>>>> stage prepare base model started <<<<<<<<<<<<]
[2024-04-05 14:42:42,454:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:42:42,459:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:42:42,459:INFO: common:Created directory at : artifacts]
[2024-04-05 14:42:42,461:INFO: common:Created directory at : artifacts/prepare_base_model]
[2024-04-05 14:42:43,070:WARNING: saving_utils:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-05 14:42:44,189:INFO: main:************************************************]
[2024-04-05 14:42:44,189:INFO: main:>>>>>>> stage prepare base model Completed <<<<<<<<<<<]
[2024-04-05 14:42:44,189:INFO: main:***********************************************]
[2024-04-05 14:42:44,189:INFO: main:>>>>>>> stage Training started <<<<<<<<<<<<]
[2024-04-05 14:42:44,195:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:42:44,198:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:42:44,199:INFO: common:Created directory at : artifacts]
[2024-04-05 14:42:44,199:INFO: common:Created directory at : artifacts\training]
[2024-04-05 14:47:00,546:INFO: main:************************************************]
[2024-04-05 14:47:00,547:INFO: main:>>>>>>> stage Training Completed <<<<<<<<<<<]
[2024-04-05 14:47:00,547:INFO: main:>>>>>>>> stage Evaluation Stage started <<<<<<<<]
[2024-04-05 14:47:00,555:INFO: common:yaml file: config\config.yaml loaded sucessfully]
[2024-04-05 14:47:00,559:INFO: common:yaml file: params.yaml loaded sucessfully]
[2024-04-05 14:47:00,559:INFO: common:Created directory at : artifacts]
[2024-04-05 14:47:51,900:INFO: common:json file saved : scores.json]
[2024-04-05 14:47:57,120:WARNING: save:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 14). These functions will not be directly callable after loading.]
[2024-04-05 14:47:58,168:INFO: builder_impl:Assets written to: C:\Users\ADMIN\AppData\Local\Temp\tmpjtwry04w\model\data\model\assets]
[2024-04-05 14:48:42,869:INFO: main:>>>>>>>> stage Evaluation Stage completed <<<<<<]
